/* This file was generated by the Pallene compiler. Do not edit by hand" */
/* Indentation and formatting courtesy of pallene/C.lua */

#include "pallene_core.h"

/* ------- */
/* Records */
/* ------- */

/* ------------------- */
/* Function Prototypes */
/* ------------------- */

static void function_01(
    lua_State *L,
    Udata *G,
    StackValue *base
);
static lua_Integer function_02(
    lua_State *L,
    Udata *G,
    StackValue *base
);
static lua_Integer function_03(
    lua_State *L,
    Udata *G,
    StackValue *base
);
static TString * function_04(
    lua_State *L,
    Udata *G,
    StackValue *base
);
static TString * function_05(
    lua_State *L,
    Udata *G,
    StackValue *base
);
static lua_Integer function_06(
    lua_State *L,
    Udata *G,
    StackValue *base
);
static TString * function_07(
    lua_State *L,
    Udata *G,
    StackValue *base
);

/* ------------------------ */
/* Function Implementations */
/* ------------------------ */

/* $init */
static void function_01(
    lua_State *L,
    Udata *G,
    StackValue *base
) {
    ptrdiff_t base_offset = savestack(L, base);
    	
}

/* Int gcctests/cse/pallene.pln:1 */
static lua_Integer function_02(
    lua_State *L,
    Udata *G,
    StackValue *base
) {
    ptrdiff_t base_offset = savestack(L, base);
    	
    return 5;
}

/* ints gcctests/cse/pallene.pln:5 */
static lua_Integer function_03(
    lua_State *L,
    Udata *G,
    StackValue *base
) {
    ptrdiff_t base_offset = savestack(L, base);
    	
    lua_Integer x1; /* b */
    lua_Integer x2; /* c */
    lua_Integer x3; /* g */
    lua_Integer x4; /* e */
    lua_Integer x5; /* a */
    lua_Integer x6;
    lua_Integer x7; /* d */
    lua_Integer x8;
    lua_Integer x9;
    	

    base = restorestack(L, base_offset);

    return 8;
}

/* String gcctests/cse/pallene.pln:15 */
static TString * function_04(
    lua_State *L,
    Udata *G,
    StackValue *base
) {
    ptrdiff_t base_offset = savestack(L, base);
    	
    return tsvalue(&G->uv[0].uv);
}

/* strings gcctests/cse/pallene.pln:19 */
static TString * function_05(
    lua_State *L,
    Udata *G,
    StackValue *base
) {
    luaD_checkstack(L, 5);
    ptrdiff_t base_offset = savestack(L, base);
    	
    TString *x1; /* b */
    TString *x2; /* c */
    TString *x3; /* g */
    TString *x4; /* e */
    TString *x5; /* a */
    TString *x6; /* d */
    TString *x7;
    TString *cse;
    	
    x1 = function_04(L, G, base + 0);
    base = restorestack(L, base_offset);
    setsvalue(L, s2v(base + 0), x1);
    x2 = x1;
    x3 = tsvalue(&G->uv[1].uv);
    x4 = tsvalue(&G->uv[2].uv);
    TString *csetmp[2];
    csetmp[0] = x1;
    csetmp[1] = x2;
    cse = pallene_string_concatN(L, 2, csetmp);

    setsvalue(L, s2v(base + 2), x4);
    {
        TString *ss[2];
        ss[0] = cse;
        ss[1] = x3;
        x5 = pallene_string_concatN(L, 2, ss);
    }
    setsvalue(L, s2v(base + 3), x5);
    luaC_condGC(L, L->top = base + 4, (void)0);
    {
        TString *ss[2];
        ss[0] = cse;
        ss[1] = x4;
        x6 = pallene_string_concatN(L, 2, ss);
    }
    setsvalue(L, s2v(base + 4), x6);
    luaC_condGC(L, L->top = base + 5, (void)0);
    {
        TString *ss[2];
        ss[0] = x5;
        ss[1] = x6; ;
        x7 = pallene_string_concatN(L, 2, ss);
    }
    setsvalue(L, s2v(base + 0), x7);
    luaC_condGC(L, L->top = base + 1, (void)0);
    return x7;
}

/* upvaluesInt gcctests/cse/pallene.pln:31 */
static lua_Integer function_06(
    lua_State *L,
    Udata *G,
    StackValue *base
) {
    ptrdiff_t base_offset = savestack(L, base);
    	
    lua_Integer x1; /* b */
    lua_Integer x2; /* c */
    lua_Integer x3; /* g */
    lua_Integer x4; /* e */
    lua_Integer x5; /* a */
    lua_Integer x6;
    lua_Integer x7; /* d */
    lua_Integer x8;
    lua_Integer x9;
    	
    x1 = 5;
    x2 = 5;
    x3 = 4;
    x4 = 3;
    x6 = intop(*, x1, x2);
    x5 = intop(+, x6, x3);
    x8 = intop(*, x1, x2);
    x7 = intop(+, x8, x4);
    x9 = intop(+, x5, x7);
    return x9;
}

/* upvaluesString gcctests/cse/pallene.pln:43 */
static TString * function_07(
    lua_State *L,
    Udata *G,
    StackValue *base
) {
    luaD_checkstack(L, 5);
    ptrdiff_t base_offset = savestack(L, base);
    	
    TString *x1; /* b */
    TString *x2; /* c */
    TString *x3; /* g */
    TString *x4; /* e */
    TString *x5; /* a */
    TString *x6; /* d */
    TString *x7;
    	
    x1 = tsvalue(&G->uv[3].uv);
    setsvalue(L, s2v(base + 0), x1);
    x2 = tsvalue(&G->uv[3].uv);
    setsvalue(L, s2v(base + 1), x2);
    x3 = tsvalue(&G->uv[1].uv);
    x4 = tsvalue(&G->uv[2].uv);
    setsvalue(L, s2v(base + 2), x4);
    {
        TString *ss[3];
        ss[0] = x1;
        ss[1] = x2;
        ss[2] = x3; ;
        x5 = pallene_string_concatN(L, 3, ss);
    }
    setsvalue(L, s2v(base + 3), x5);
    luaC_condGC(L, L->top = base + 4, (void)0);
    {
        TString *ss[3];
        ss[0] = x1;
        ss[1] = x2;
        ss[2] = x4; ;
        x6 = pallene_string_concatN(L, 3, ss);
    }
    setsvalue(L, s2v(base + 4), x6);
    luaC_condGC(L, L->top = base + 5, (void)0);
    {
        TString *ss[2];
        ss[0] = x5;
        ss[1] = x6; ;
        x7 = pallene_string_concatN(L, 2, ss);
    }
    setsvalue(L, s2v(base + 0), x7);
    luaC_condGC(L, L->top = base + 1, (void)0);
    return x7;
}

/* ------- */
/* Exports */
/* ------- */

static int function_01_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 0)) {
        pallene_runtime_arity_error(L, "$init", 0, nargs);
    }
    	
    function_01(L, G, L->top);
    return 0;
}

static int function_03_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 0)) {
        pallene_runtime_arity_error(L, "ints", 0, nargs);
    }
    	
    lua_Integer ret1;
    ret1 = function_03(L, G, L->top);
    setivalue(s2v(L->top), ret1);
    L->top++;
    return 1;
}

static int function_05_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 0)) {
        pallene_runtime_arity_error(L, "strings", 0, nargs);
    }
    	
    TString *ret1;
    ret1 = function_05(L, G, L->top);
    setsvalue(L, s2v(L->top), ret1);
    L->top++;
    return 1;
}

static int function_06_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 0)) {
        pallene_runtime_arity_error(L, "upvaluesInt", 0, nargs);
    }
    	
    lua_Integer ret1;
    ret1 = function_06(L, G, L->top);
    setivalue(s2v(L->top), ret1);
    L->top++;
    return 1;
}

static int function_07_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 0)) {
        pallene_runtime_arity_error(L, "upvaluesString", 0, nargs);
    }
    	
    TString *ret1;
    ret1 = function_07(L, G, L->top);
    setsvalue(L, s2v(L->top), ret1);
    L->top++;
    return 1;
}

int luaopen_gcctests_cse_pallene_mod(lua_State *L)
{
    luaL_checkversion(L);
    	
    /* Constants */
    	
    lua_newuserdatauv(L, 0, 8);
    int globals = lua_gettop(L);
    	
    lua_pushstring(L, "ola");
    lua_setiuservalue(L, globals, 1);
    	
    lua_pushstring(L, "a");
    lua_setiuservalue(L, globals, 2);
    	
    lua_pushstring(L, "b");
    lua_setiuservalue(L, globals, 3);
    	
    lua_pushstring(L, "aa");
    lua_setiuservalue(L, globals, 4);
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_03_lua, 1);
    lua_setiuservalue(L, globals, 5);
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_05_lua, 1);
    lua_setiuservalue(L, globals, 6);
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_06_lua, 1);
    lua_setiuservalue(L, globals, 7);
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_07_lua, 1);
    lua_setiuservalue(L, globals, 8);
    	
    /* Variables & Initializers */
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_01_lua, 1);
    lua_call(L, 0, 0);
    	
    /* Exports */
    	
    lua_newtable(L);
    int export_table = lua_gettop(L);
    	
    lua_pushstring(L, "ints");
    lua_getiuservalue(L, globals, 5);
    lua_settable(L, export_table);
    	
    lua_pushstring(L, "strings");
    lua_getiuservalue(L, globals, 6);
    lua_settable(L, export_table);
    	
    lua_pushstring(L, "upvaluesInt");
    lua_getiuservalue(L, globals, 7);
    lua_settable(L, export_table);
    	
    lua_pushstring(L, "upvaluesString");
    lua_getiuservalue(L, globals, 8);
    lua_settable(L, export_table);
    	
    lua_pushvalue(L, export_table);
    return 1;
}

