/* This file was generated by the Pallene compiler. Do not edit by hand" */
/* Indentation and formatting courtesy of pallene/C.lua */

#include "pallene_core.h"

/* ------- */
/* Records */
/* ------- */

/* ------------------- */
/* Function Prototypes */
/* ------------------- */

static void function_01(
    lua_State *L,
    Udata *G,
    StackValue *base
);
static lua_Integer function_02(
    lua_State *L,
    Udata *G,
    StackValue *base
);

/* ------------------------ */
/* Function Implementations */
/* ------------------------ */

/* $init */
static void function_01(
    lua_State *L,
    Udata *G,
    StackValue *base
) {
    	
    setivalue(&G->uv[0].uv, 0);
    setivalue(&G->uv[1].uv, 0);
    setivalue(&G->uv[2].uv, 0);
}

/* f cmppalleneC/address.pln:5 */
static lua_Integer function_02(
    lua_State *L,
    Udata *G,
    StackValue *base
) {
    lua_Integer x1;
    lua_Integer x2;
    lua_Integer x3;
    lua_Integer x4;
    lua_Integer x5;
    	
    setivalue(&G->uv[0].uv, 3);
    setivalue(&G->uv[1].uv, 5);
    setivalue(&G->uv[2].uv, 7);
    x3 = ivalue(&G->uv[0].uv);
    x4 = ivalue(&G->uv[1].uv);
    x2 = intop(+, x3, x4);
    x5 = ivalue(&G->uv[2].uv);
    x1 = intop(+, x2, x5);
    return x1;
}

/* ------- */
/* Exports */
/* ------- */

static int function_01_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 0)) {
        pallene_runtime_arity_error(L, "$init", 0, nargs);
    }
    	
    function_01(L, G, L->top);
    return 0;
}

static int function_02_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 0)) {
        pallene_runtime_arity_error(L, "f", 0, nargs);
    }
    	
    lua_Integer ret1;
    ret1 = function_02(L, G, L->top);
    setivalue(s2v(L->top), ret1);
    L->top++;
    return 1;
}

int luaopen_cmppalleneC_address(lua_State *L)
{
    luaL_checkversion(L);
    	
    lua_newuserdatauv(L, 0, 3);
    int globals = lua_gettop(L);
    	
    lua_createtable(L, 2, 0);
    int closures = lua_gettop(L);
    	
    lua_newtable(L);
    int export_table = lua_gettop(L);
    	
    /* Closures */
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_01_lua, 1);
    lua_seti(L, closures, 1);
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_02_lua, 1);
    lua_seti(L, closures, 2);
    	
    /* Global values */
    	
    // Run toplevel statements & initialize globals
    lua_geti(L, closures, 1);
    lua_call(L, 0, 0);
    	
    /* Exports */
    	
    lua_pushstring(L, "f");
    lua_geti(L, closures, 2);
    lua_settable(L, export_table);
    	
    lua_pushvalue(L, export_table);
    return 1;
}

