/* This file was generated by the Pallene compiler. Do not edit by hand" */
/* Indentation and formatting courtesy of pallene/C.lua */

#include "pallene_core.h"

/* ------- */
/* Records */
/* ------- */

/* ------------------- */
/* Function Prototypes */
/* ------------------- */

static void function_01(
    lua_State *L,
    Udata *G,
    StackValue *base
);
static lua_Integer function_02(
    lua_State *L,
    Udata *G,
    StackValue *base,
    Table *x1, /* p */
    lua_Integer x2  /* i */
);
static void function_03(
    lua_State *L,
    Udata *G,
    StackValue *base,
    lua_Integer x1  /* n */
);

/* ------------------------ */
/* Function Implementations */
/* ------------------------ */

/* $init */
static void function_01(
    lua_State *L,
    Udata *G,
    StackValue *base
) {
    luaD_checkstack(L, 1);
    Table *x1;
    	
    x1 = pallene_createtable(L, 3, 0);
    sethvalue(L, s2v(base + 0), x1);
    luaC_condGC(L, L->top = base + 1, (void)0);
    {
        pallene_renormalize_array(L, x1, 1, 3);
        TValue *slot = &x1->array[1 - 1];
        setivalue(slot, 1);
    }
    {
        pallene_renormalize_array(L, x1, 2, 3);
        TValue *slot = &x1->array[2 - 1];
        setivalue(slot, 2);
    }
    {
        pallene_renormalize_array(L, x1, 3, 3);
        TValue *slot = &x1->array[3 - 1];
        setivalue(slot, 3);
    }
    sethvalue(L, &G->uv[0].uv, x1);
    pallene_barrierback_collectable_child(L, G, x1);
}

/* f cmppalleneC/alias_const.pln:5 */
static lua_Integer function_02(
    lua_State *L,
    Udata *G,
    StackValue *base,
    Table *x1, /* p */
    lua_Integer x2  /* i */
) {
    luaD_checkstack(L, 1);
    lua_Integer x3; /* x */
    lua_Integer x4; /* y */
    Table *x5; /* q */
    lua_Integer x6;
    	
    x3 = 0;
    x4 = 0;
    x5 = hvalue(&G->uv[0].uv);
    sethvalue(L, s2v(base + 0), x5);
    {
        pallene_renormalize_array(L, x5, x2, 9);
        TValue *slot = &x5->array[x2 - 1];
        if (PALLENE_UNLIKELY(!ttisinteger(slot))) {
            pallene_runtime_tag_check_error(L,
                9, LUA_TNUMINT, rawtt(slot),
                "array element");
        }
        x3 = ivalue(slot);
    }
    x1 = pallene_createtable(L, 0, 0);
    luaC_condGC(L, L->top = base + 1, (void)0);
    {
        pallene_renormalize_array(L, x5, x2, 11);
        TValue *slot = &x5->array[x2 - 1];
        if (PALLENE_UNLIKELY(!ttisinteger(slot))) {
            pallene_runtime_tag_check_error(L,
                11, LUA_TNUMINT, rawtt(slot),
                "array element");
        }
        x4 = ivalue(slot);
    }
    x6 = intop(+, x3, x4);
    return x6;
}

/* test cmppalleneC/alias_const.pln:28 */
static void function_03(
    lua_State *L,
    Udata *G,
    StackValue *base,
    lua_Integer x1  /* n */
) {
    luaD_checkstack(L, 1);
    lua_Integer x2; /* i */
    Table *x3;
    	
    PALLENE_INT_FOR_LOOP_BEGIN(x2, 0, x1, 1)
    {
        x3 = pallene_createtable(L, 3, 0);
        sethvalue(L, s2v(base + 0), x3);
        luaC_condGC(L, L->top = base + 1, (void)0);
        {
            pallene_renormalize_array(L, x3, 1, 30);
            TValue *slot = &x3->array[1 - 1];
            setivalue(slot, 1);
        }
        {
            pallene_renormalize_array(L, x3, 2, 30);
            TValue *slot = &x3->array[2 - 1];
            setivalue(slot, 2);
        }
        {
            pallene_renormalize_array(L, x3, 3, 30);
            TValue *slot = &x3->array[3 - 1];
            setivalue(slot, 3);
        }
        {
            StackValue *old_stack = L->stack;
            function_02(L, G, base + 1, x3, 1);
            base = L->stack + (base - old_stack);
        }
    }
    PALLENE_INT_FOR_LOOP_END
}

/* ------- */
/* Exports */
/* ------- */

static int function_01_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 0)) {
        pallene_runtime_arity_error(L, "$init", 0, nargs);
    }
    	
    function_01(L, G, L->top);
    return 0;
}

static int function_02_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 2)) {
        pallene_runtime_arity_error(L, "f", 2, nargs);
    }
    	
    Table *x1;
    lua_Integer x2;
    	
    if (PALLENE_UNLIKELY(!ttistable(s2v(base + 1)))) {
        pallene_runtime_tag_check_error(L,
            5, LUA_TTABLE, rawtt(s2v(base + 1)),
            "argument '%s'", "p");
    }
    x1 = hvalue(s2v(base + 1));
    	
    if (PALLENE_UNLIKELY(!ttisinteger(s2v(base + 2)))) {
        pallene_runtime_tag_check_error(L,
            5, LUA_TNUMINT, rawtt(s2v(base + 2)),
            "argument '%s'", "i");
    }
    x2 = ivalue(s2v(base + 2));
    	
    lua_Integer ret1;
    ret1 = function_02(L, G, L->top, x1, x2);
    setivalue(s2v(L->top), ret1);
    L->top++;
    return 1;
}

static int function_03_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 1)) {
        pallene_runtime_arity_error(L, "test", 1, nargs);
    }
    	
    lua_Integer x1;
    	
    if (PALLENE_UNLIKELY(!ttisinteger(s2v(base + 1)))) {
        pallene_runtime_tag_check_error(L,
            28, LUA_TNUMINT, rawtt(s2v(base + 1)),
            "argument '%s'", "n");
    }
    x1 = ivalue(s2v(base + 1));
    	
    function_03(L, G, L->top, x1);
    return 0;
}

int luaopen_cmppalleneC_alias_const(lua_State *L)
{
    luaL_checkversion(L);
    	
    lua_newuserdatauv(L, 0, 1);
    int globals = lua_gettop(L);
    	
    lua_createtable(L, 3, 0);
    int closures = lua_gettop(L);
    	
    lua_newtable(L);
    int export_table = lua_gettop(L);
    	
    /* Closures */
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_01_lua, 1);
    lua_seti(L, closures, 1);
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_02_lua, 1);
    lua_seti(L, closures, 2);
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_03_lua, 1);
    lua_seti(L, closures, 3);
    	
    /* Global values */
    	
    // Run toplevel statements & initialize globals
    lua_geti(L, closures, 1);
    lua_call(L, 0, 0);
    	
    /* Exports */
    	
    lua_pushstring(L, "f");
    lua_geti(L, closures, 2);
    lua_settable(L, export_table);
    	
    lua_pushstring(L, "test");
    lua_geti(L, closures, 3);
    lua_settable(L, export_table);
    	
    lua_pushvalue(L, export_table);
    return 1;
}

