/* This file was generated by the Pallene compiler. Do not edit by hand" */
/* Indentation and formatting courtesy of pallene/C.lua */

#include "pallene_core.h"

/* ------- */
/* Records */
/* ------- */

/* ------------------- */
/* Function Prototypes */
/* ------------------- */

static void function_01(
    lua_State *L,
    Udata *G,
    StackValue *base
);
static lua_Integer function_02(
    lua_State *L,
    Udata *G,
    StackValue *base,
    Table *x1, /* ps */
    Table *x2  /* pi */
);

/* ------------------------ */
/* Function Implementations */
/* ------------------------ */

/* $init */
static void function_01(
    lua_State *L,
    Udata *G,
    StackValue *base
) {
    	
}

/* f cmppalleneC/alias_type.pln:1 */
static lua_Integer function_02(
    lua_State *L,
    Udata *G,
    StackValue *base,
    Table *x1, /* ps */
    Table *x2  /* pi */
) {
    lua_Integer x3; /* i */
    lua_Integer x4; /* j */
    lua_Integer x5;
    	
    {
        pallene_renormalize_array(L, x2, 0, 2);
        TValue *slot = &x2->array[0 - 1];
        if (PALLENE_UNLIKELY(!ttisinteger(slot))) {
            pallene_runtime_tag_check_error(L,
                2, LUA_TNUMINT, rawtt(slot),
                "array element");
        }
        x3 = ivalue(slot);
    }
    x1 = pallene_createtable(L, 0, 0);
    luaC_condGC(L, L->top = base + 0, (void)0);
    {
        pallene_renormalize_array(L, x2, 0, 4);
        TValue *slot = &x2->array[0 - 1];
        if (PALLENE_UNLIKELY(!ttisinteger(slot))) {
            pallene_runtime_tag_check_error(L,
                4, LUA_TNUMINT, rawtt(slot),
                "array element");
        }
        x4 = ivalue(slot);
    }
    x5 = intop(+, x3, x4);
    return x5;
}

/* ------- */
/* Exports */
/* ------- */

static int function_01_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 0)) {
        pallene_runtime_arity_error(L, "$init", 0, nargs);
    }
    	
    function_01(L, G, L->top);
    return 0;
}

static int function_02_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 2)) {
        pallene_runtime_arity_error(L, "f", 2, nargs);
    }
    	
    Table *x1;
    Table *x2;
    	
    if (PALLENE_UNLIKELY(!ttistable(s2v(base + 1)))) {
        pallene_runtime_tag_check_error(L,
            1, LUA_TTABLE, rawtt(s2v(base + 1)),
            "argument '%s'", "ps");
    }
    x1 = hvalue(s2v(base + 1));
    	
    if (PALLENE_UNLIKELY(!ttistable(s2v(base + 2)))) {
        pallene_runtime_tag_check_error(L,
            1, LUA_TTABLE, rawtt(s2v(base + 2)),
            "argument '%s'", "pi");
    }
    x2 = hvalue(s2v(base + 2));
    	
    lua_Integer ret1;
    ret1 = function_02(L, G, L->top, x1, x2);
    setivalue(s2v(L->top), ret1);
    L->top++;
    return 1;
}

int luaopen_cmppalleneC_alias_type(lua_State *L)
{
    luaL_checkversion(L);
    	
    lua_newuserdatauv(L, 0, 0);
    int globals = lua_gettop(L);
    	
    lua_createtable(L, 2, 0);
    int closures = lua_gettop(L);
    	
    lua_newtable(L);
    int export_table = lua_gettop(L);
    	
    /* Closures */
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_01_lua, 1);
    lua_seti(L, closures, 1);
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_02_lua, 1);
    lua_seti(L, closures, 2);
    	
    /* Global values */
    	
    // Run toplevel statements & initialize globals
    lua_geti(L, closures, 1);
    lua_call(L, 0, 0);
    	
    /* Exports */
    	
    lua_pushstring(L, "f");
    lua_geti(L, closures, 2);
    lua_settable(L, export_table);
    	
    lua_pushvalue(L, export_table);
    return 1;
}

