/* This file was generated by the Pallene compiler. Do not edit by hand" */
/* Indentation and formatting courtesy of pallene/C.lua */

#include "pallene_core.h"

/* ------- */
/* Records */
/* ------- */

/* ------------------- */
/* Function Prototypes */
/* ------------------- */

static void function_01(
    lua_State *L,
    Udata *G,
    StackValue *base
);
static void function_02(
    lua_State *L,
    Udata *G,
    StackValue *base,
    lua_Integer x1, /* i */
    lua_Integer x2  /* j */
);

/* ------------------------ */
/* Function Implementations */
/* ------------------------ */

/* $init */
static void function_01(
    lua_State *L,
    Udata *G,
    StackValue *base
) {
    luaD_checkstack(L, 1);
    Table *x1;
    Table *x2;
    	
    x1 = pallene_createtable(L, 0, 0);
    sethvalue(L, s2v(base + 0), x1);
    luaC_condGC(L, L->top = base + 1, (void)0);
    sethvalue(L, &G->uv[0].uv, x1);
    pallene_barrierback_collectable_child(L, G, x1);
    x2 = pallene_createtable(L, 0, 0);
    sethvalue(L, s2v(base + 0), x2);
    luaC_condGC(L, L->top = base + 1, (void)0);
    sethvalue(L, &G->uv[1].uv, x2);
    pallene_barrierback_collectable_child(L, G, x2);
}

/* f cmppalleneC/alias_address.pln:4 */
static void function_02(
    lua_State *L,
    Udata *G,
    StackValue *base,
    lua_Integer x1, /* i */
    lua_Integer x2  /* j */
) {
    luaD_checkstack(L, 1);
    lua_Integer x3; /* y */
    lua_Integer x4; /* x */
    Table *x5; /* p */
    Table *x6; /* q */
    	
    x3 = 0;
    x4 = 0;
    x5 = hvalue(&G->uv[0].uv);
    sethvalue(L, s2v(base + 0), x5);
    x6 = hvalue(&G->uv[1].uv);
    {
        pallene_renormalize_array(L, x6, 3, 9);
        TValue *slot = &x6->array[3 - 1];
        if (PALLENE_UNLIKELY(!ttisinteger(slot))) {
            pallene_runtime_tag_check_error(L,
                9, LUA_TNUMINT, rawtt(slot),
                "array element");
        }
        x4 = ivalue(slot);
    }
    x5 = pallene_createtable(L, 0, 0);
    sethvalue(L, s2v(base + 0), x5);
    luaC_condGC(L, L->top = base + 1, (void)0);
    {
        pallene_renormalize_array(L, x5, 3, 11);
        TValue *slot = &x5->array[3 - 1];
        if (PALLENE_UNLIKELY(!ttisinteger(slot))) {
            pallene_runtime_tag_check_error(L,
                11, LUA_TNUMINT, rawtt(slot),
                "array element");
        }
        x3 = ivalue(slot);
    }
    {
        StackValue *old_stack = L->stack;
        function_02(L, G, base + 0, x4, x3);
        base = L->stack + (base - old_stack);
    }
}

/* ------- */
/* Exports */
/* ------- */

static int function_01_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 0)) {
        pallene_runtime_arity_error(L, "$init", 0, nargs);
    }
    	
    function_01(L, G, L->top);
    return 0;
}

static int function_02_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 2)) {
        pallene_runtime_arity_error(L, "f", 2, nargs);
    }
    	
    lua_Integer x1;
    lua_Integer x2;
    	
    if (PALLENE_UNLIKELY(!ttisinteger(s2v(base + 1)))) {
        pallene_runtime_tag_check_error(L,
            4, LUA_TNUMINT, rawtt(s2v(base + 1)),
            "argument '%s'", "i");
    }
    x1 = ivalue(s2v(base + 1));
    	
    if (PALLENE_UNLIKELY(!ttisinteger(s2v(base + 2)))) {
        pallene_runtime_tag_check_error(L,
            4, LUA_TNUMINT, rawtt(s2v(base + 2)),
            "argument '%s'", "j");
    }
    x2 = ivalue(s2v(base + 2));
    	
    function_02(L, G, L->top, x1, x2);
    return 0;
}

int luaopen_cmppalleneC_alias_address(lua_State *L)
{
    luaL_checkversion(L);
    	
    lua_newuserdatauv(L, 0, 2);
    int globals = lua_gettop(L);
    	
    lua_createtable(L, 2, 0);
    int closures = lua_gettop(L);
    	
    lua_newtable(L);
    int export_table = lua_gettop(L);
    	
    /* Closures */
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_01_lua, 1);
    lua_seti(L, closures, 1);
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_02_lua, 1);
    lua_seti(L, closures, 2);
    	
    /* Global values */
    	
    // Run toplevel statements & initialize globals
    lua_geti(L, closures, 1);
    lua_call(L, 0, 0);
    	
    /* Exports */
    	
    lua_pushstring(L, "f");
    lua_geti(L, closures, 2);
    lua_settable(L, export_table);
    	
    lua_pushvalue(L, export_table);
    return 1;
}

