/* This file was generated by the Pallene compiler. Do not edit by hand" */
/* Indentation and formatting courtesy of pallene/C.lua */

#include "pallene_core.h"

/* ------- */
/* Records */
/* ------- */

/* ------------------- */
/* Function Prototypes */
/* ------------------- */

static void function_01(
    lua_State *L,
    Udata *G,
    StackValue *base
);
static void function_02(
    lua_State *L,
    Udata *G,
    StackValue *base
);

/* ------------------------ */
/* Function Implementations */
/* ------------------------ */

/* $init */
static void function_01(
    lua_State *L,
    Udata *G,
    StackValue *base
) {
    	
}

/* f cmppalleneC/array_bounds.pln:1 */
static void function_02(
    lua_State *L,
    Udata *G,
    StackValue *base
) {
    luaD_checkstack(L, 1);
    Table *x1; /* p */
    lua_Integer x2; /* unused */
    lua_Integer x3; /* unused2 */
    	
    x1 = pallene_createtable(L, 3, 0);
    sethvalue(L, s2v(base + 0), x1);
    luaC_condGC(L, L->top = base + 1, (void)0);
    {
        pallene_renormalize_array(L, x1, 1, 2);
        TValue *slot = &x1->array[1 - 1];
        setivalue(slot, 1);
    }
    {
        pallene_renormalize_array(L, x1, 2, 2);
        TValue *slot = &x1->array[2 - 1];
        setivalue(slot, 2);
    }
    {
        pallene_renormalize_array(L, x1, 3, 2);
        TValue *slot = &x1->array[3 - 1];
        setivalue(slot, 4);
    }
    {
        pallene_renormalize_array(L, x1, 1, 3);
        TValue *slot = &x1->array[1 - 1];
        if (PALLENE_UNLIKELY(!ttisinteger(slot))) {
            pallene_runtime_tag_check_error(L,
                3, LUA_TNUMINT, rawtt(slot),
                "array element");
        }
        x2 = ivalue(slot);
    }
    {
        pallene_renormalize_array(L, x1, 2, 4);
        TValue *slot = &x1->array[2 - 1];
        if (PALLENE_UNLIKELY(!ttisinteger(slot))) {
            pallene_runtime_tag_check_error(L,
                4, LUA_TNUMINT, rawtt(slot),
                "array element");
        }
        x3 = ivalue(slot);
    }
    return;
}

/* ------- */
/* Exports */
/* ------- */

static int function_01_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 0)) {
        pallene_runtime_arity_error(L, "$init", 0, nargs);
    }
    	
    function_01(L, G, L->top);
    return 0;
}

static int function_02_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 0)) {
        pallene_runtime_arity_error(L, "f", 0, nargs);
    }
    	
    function_02(L, G, L->top);
    return 0;
}

int luaopen_cmppalleneC_array_bounds(lua_State *L)
{
    luaL_checkversion(L);
    	
    lua_newuserdatauv(L, 0, 0);
    int globals = lua_gettop(L);
    	
    lua_createtable(L, 2, 0);
    int closures = lua_gettop(L);
    	
    lua_newtable(L);
    int export_table = lua_gettop(L);
    	
    /* Closures */
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_01_lua, 1);
    lua_seti(L, closures, 1);
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_02_lua, 1);
    lua_seti(L, closures, 2);
    	
    /* Global values */
    	
    // Run toplevel statements & initialize globals
    lua_geti(L, closures, 1);
    lua_call(L, 0, 0);
    	
    /* Exports */
    	
    lua_pushstring(L, "f");
    lua_geti(L, closures, 2);
    lua_settable(L, export_table);
    	
    lua_pushvalue(L, export_table);
    return 1;
}

