/* This file was generated by the Pallene compiler. Do not edit by hand" */
/* Indentation and formatting courtesy of pallene/C.lua */

#include "pallene_core.h"

/* ------- */
/* Records */
/* ------- */

/* ------------------- */
/* Function Prototypes */
/* ------------------- */

static void function_01(
    lua_State *L,
    Udata *G,
    StackValue *base
);
static lua_Integer function_02(
    lua_State *L,
    Udata *G,
    StackValue *base
);
static Table * function_03(
    lua_State *L,
    Udata *G,
    StackValue *base
);
static TString * function_04(
    lua_State *L,
    Udata *G,
    StackValue *base
);
static lua_Integer function_05(
    lua_State *L,
    Udata *G,
    StackValue *base
);
static lua_Integer function_06(
    lua_State *L,
    Udata *G,
    StackValue *base
);
static lua_Integer function_07(
    lua_State *L,
    Udata *G,
    StackValue *base
);
static lua_Integer function_08(
    lua_State *L,
    Udata *G,
    StackValue *base
);
static lua_Integer function_09(
    lua_State *L,
    Udata *G,
    StackValue *base
);
static lua_Integer function_10(
    lua_State *L,
    Udata *G,
    StackValue *base
);

/* ------------------------ */
/* Function Implementations */
/* ------------------------ */

/* $init */
static void function_01(
    lua_State *L,
    Udata *G,
    StackValue *base
) {
    ptrdiff_t base_offset = savestack(L, base);
    	
}

/* simple gcctests/constantpropagation/pallene.pln:1 */
static lua_Integer function_02(
    lua_State *L,
    Udata *G,
    StackValue *base
) {
    ptrdiff_t base_offset = savestack(L, base);
    	
    lua_Integer x1; /* x */
    lua_Integer x2; /* y */
    	
    x1 = 5;
    x2 = intop(+, 3, x1);
    return x2;
}

/* table gcctests/constantpropagation/pallene.pln:7 */
static Table * function_03(
    lua_State *L,
    Udata *G,
    StackValue *base
) {
    luaD_checkstack(L, 1);
    ptrdiff_t base_offset = savestack(L, base);
    	
    Table *x1; /* x */
    Table *x2; /* y */
    	
    x1 = pallene_createtable(L, 2, 0);
    sethvalue(L, s2v(base + 0), x1);
    luaC_condGC(L, L->top = base + 1, (void)0);
    {
        pallene_renormalize_array(L, x1, 1, 8);
        TValue *slot = &x1->array[1 - 1];
        setivalue(slot, 1);
    }
    {
        pallene_renormalize_array(L, x1, 2, 8);
        TValue *slot = &x1->array[2 - 1];
        setivalue(slot, 2);
    }
    x2 = x1;
    return x2;
}

/* String gcctests/constantpropagation/pallene.pln:12 */
static TString * function_04(
    lua_State *L,
    Udata *G,
    StackValue *base
) {
    ptrdiff_t base_offset = savestack(L, base);
    	
    TString *x1; /* x */
    TString *x2; /* y */
    	
    x1 = tsvalue(&G->uv[0].uv);
    x2 = x1;
    return x2;
}

/* withif gcctests/constantpropagation/pallene.pln:18 */
static lua_Integer function_05(
    lua_State *L,
    Udata *G,
    StackValue *base
) {
    ptrdiff_t base_offset = savestack(L, base);
    	
    lua_Integer x1; /* x */
    lua_Integer x2; /* y */
    	
    x1 = 5;
    x2 = 0;
    x2 = intop(+, 3, x1);
    return x2;
}

/* withifcond gcctests/constantpropagation/pallene.pln:27 */
static lua_Integer function_06(
    lua_State *L,
    Udata *G,
    StackValue *base
) {
    ptrdiff_t base_offset = savestack(L, base);
    	
    lua_Integer x1; /* x */
    lua_Integer x2; /* y */
    int x3;
    	
    x1 = 5;
    x2 = 0;
    x3 = (x1 > 3);
    if (x3) {
        x2 = intop(+, 3, x1);
    }
    return x2;
}

/* withloop gcctests/constantpropagation/pallene.pln:36 */
static lua_Integer function_07(
    lua_State *L,
    Udata *G,
    StackValue *base
) {
    ptrdiff_t base_offset = savestack(L, base);
    	
    lua_Integer x1; /* x */
    lua_Integer x2; /* i */
    int x3;
    lua_Integer x4; /* y */
    	
  
    return 8;
}

/* f gcctests/constantpropagation/pallene.pln:47 */
static lua_Integer function_08(
    lua_State *L,
    Udata *G,
    StackValue *base
) {
    ptrdiff_t base_offset = savestack(L, base);
    	
    return 5;
}

/* withcall gcctests/constantpropagation/pallene.pln:49 */
static lua_Integer function_09(
    lua_State *L,
    Udata *G,
    StackValue *base
) {
    ptrdiff_t base_offset = savestack(L, base);
    	
    lua_Integer x1; /* x */
    lua_Integer x2; /* x */
    lua_Integer x3; /* y */
    	
    x1 = 3;
    x2 = function_08(L, G, base + 0);
    base = restorestack(L, base_offset);
    x3 = intop(+, 3, x2);
    return x3;
}

/* upvalue gcctests/constantpropagation/pallene.pln:57 */
static lua_Integer function_10(
    lua_State *L,
    Udata *G,
    StackValue *base
) {
    ptrdiff_t base_offset = savestack(L, base);
    	
    lua_Integer x1; /* y */
    lua_Integer x2;
    	
    x2 = 5;
    x1 = intop(+, x2, 3);
    return x1;
}

/* ------- */
/* Exports */
/* ------- */

static int function_01_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 0)) {
        pallene_runtime_arity_error(L, "$init", 0, nargs);
    }
    	
    function_01(L, G, L->top);
    return 0;
}

static int function_02_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 0)) {
        pallene_runtime_arity_error(L, "simple", 0, nargs);
    }
    	
    lua_Integer ret1;
    ret1 = function_02(L, G, L->top);
    setivalue(s2v(L->top), ret1);
    L->top++;
    return 1;
}

static int function_03_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 0)) {
        pallene_runtime_arity_error(L, "table", 0, nargs);
    }
    	
    Table *ret1;
    ret1 = function_03(L, G, L->top);
    sethvalue(L, s2v(L->top), ret1);
    L->top++;
    return 1;
}

static int function_04_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 0)) {
        pallene_runtime_arity_error(L, "String", 0, nargs);
    }
    	
    TString *ret1;
    ret1 = function_04(L, G, L->top);
    setsvalue(L, s2v(L->top), ret1);
    L->top++;
    return 1;
}

static int function_05_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 0)) {
        pallene_runtime_arity_error(L, "withif", 0, nargs);
    }
    	
    lua_Integer ret1;
    ret1 = function_05(L, G, L->top);
    setivalue(s2v(L->top), ret1);
    L->top++;
    return 1;
}

static int function_06_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 0)) {
        pallene_runtime_arity_error(L, "withifcond", 0, nargs);
    }
    	
    lua_Integer ret1;
    ret1 = function_06(L, G, L->top);
    setivalue(s2v(L->top), ret1);
    L->top++;
    return 1;
}

static int function_07_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 0)) {
        pallene_runtime_arity_error(L, "withloop", 0, nargs);
    }
    	
    lua_Integer ret1;
    ret1 = function_07(L, G, L->top);
    setivalue(s2v(L->top), ret1);
    L->top++;
    return 1;
}

static int function_09_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 0)) {
        pallene_runtime_arity_error(L, "withcall", 0, nargs);
    }
    	
    lua_Integer ret1;
    ret1 = function_09(L, G, L->top);
    setivalue(s2v(L->top), ret1);
    L->top++;
    return 1;
}

static int function_10_lua(lua_State *L)
{
    StackValue *base = L->ci->func;
    CClosure *func = clCvalue(s2v(base));
    Udata *G = uvalue(&func->upvalue[0]);
    	
    int nargs = lua_gettop(L);
    if (PALLENE_UNLIKELY(nargs != 0)) {
        pallene_runtime_arity_error(L, "upvalue", 0, nargs);
    }
    	
    lua_Integer ret1;
    ret1 = function_10(L, G, L->top);
    setivalue(s2v(L->top), ret1);
    L->top++;
    return 1;
}

int luaopen_gcctests_constantpropagation_pallene_mod(lua_State *L)
{
    luaL_checkversion(L);
    	
    /* Constants */
    	
    lua_newuserdatauv(L, 0, 9);
    int globals = lua_gettop(L);
    	
    lua_pushstring(L, "abc");
    lua_setiuservalue(L, globals, 1);
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_02_lua, 1);
    lua_setiuservalue(L, globals, 2);
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_03_lua, 1);
    lua_setiuservalue(L, globals, 3);
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_04_lua, 1);
    lua_setiuservalue(L, globals, 4);
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_05_lua, 1);
    lua_setiuservalue(L, globals, 5);
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_06_lua, 1);
    lua_setiuservalue(L, globals, 6);
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_07_lua, 1);
    lua_setiuservalue(L, globals, 7);
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_09_lua, 1);
    lua_setiuservalue(L, globals, 8);
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_10_lua, 1);
    lua_setiuservalue(L, globals, 9);
    	
    /* Variables & Initializers */
    	
    lua_pushvalue(L, globals);
    lua_pushcclosure(L, function_01_lua, 1);
    lua_call(L, 0, 0);
    	
    /* Exports */
    	
    lua_newtable(L);
    int export_table = lua_gettop(L);
    	
    lua_pushstring(L, "simple");
    lua_getiuservalue(L, globals, 2);
    lua_settable(L, export_table);
    	
    lua_pushstring(L, "table");
    lua_getiuservalue(L, globals, 3);
    lua_settable(L, export_table);
    	
    lua_pushstring(L, "String");
    lua_getiuservalue(L, globals, 4);
    lua_settable(L, export_table);
    	
    lua_pushstring(L, "withif");
    lua_getiuservalue(L, globals, 5);
    lua_settable(L, export_table);
    	
    lua_pushstring(L, "withifcond");
    lua_getiuservalue(L, globals, 6);
    lua_settable(L, export_table);
    	
    lua_pushstring(L, "withloop");
    lua_getiuservalue(L, globals, 7);
    lua_settable(L, export_table);
    	
    lua_pushstring(L, "withcall");
    lua_getiuservalue(L, globals, 8);
    lua_settable(L, export_table);
    	
    lua_pushstring(L, "upvalue");
    lua_getiuservalue(L, globals, 9);
    lua_settable(L, export_table);
    	
    lua_pushvalue(L, export_table);
    return 1;
}

