# This is the configuration file for our CI via Github Actions.
#
# See:
#   - https://github.com/actions/checkout
#   - https://github.com/leafo/gh-actions-lua
#   - https://github.com/leafo/gh-actions-luarocks

name: Github Actions CI

on: [ pull_request ]

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: leafo/gh-actions-lua@v8.0.0
            - uses: leafo/gh-actions-luarocks@v4.0.0

            - name: Build
              run: |
                  luarocks make
                  make linux-noreadline

            - name: Install Busted
              run: luarocks install busted

            - name: Run Tests
              run: busted -o gtest -v ./spec

